### ISSUE TITLE
error importing GeoApps.ConstUtils.deg2m

### ISSUE THREAD

**Issue by AminFazlKazemi** [miniufo/xcontour#2]
Hi

I am trying to run the LWA code. 
I find it difficult install ing geoapps, even thought it is a great package. It seems only we are trying to convert LatLong grid to meters using GeoApps. Is there any problem to the code if we substitute GeoApps function?

for example:

    a=6378137.
    b=6356752.3
    earth_radius=1000.*numpy.sqrt((numpy.power(a*a*numpy.cos(numpy.radians(lat)),2.)+numpy.power(b*b*numpy.sin(numpy.radians(lat)),2.))/(numpy.power(a*numpy.cos(numpy.radians(lat)),2.)+numpy.power(b*numpy.sin(numpy.radians(lat)),2.)))
    deg2m=earth_radius*numpy.cos(numpy.radians(lat))

**Comment by miniufo** [comment]
See #1  and closing this now.
